### ISSUE TITLE
why you stopped using exampleSite?

### ISSUE THREAD

**Issue by netgala** [zerostaticthemes/hugo-serif-theme#34]
Hi,

I'm trying to use your hugo theme, and I'm wondering why you stopped using the exampleSite feature of Hugo (which is a pretty cool feature) in the commit e2837e4ae002c8b31475f2333bcd2a53360ed2d4

Thanks

**Comment by JugglerX** [comment]
@netgala Mainly because of the following cons.

* Much harder to install the theme without having to copy and paste files etc.
* harder to deploy to Netlify. Yes you can write a clever build command but then the user has to replace this once they have installed the exampleSite, so again makes it harder to install.
* harder to deploy to Stackbit. Stackbit previously did not support install from exampleSite, but now it does.

Can you tell me the benefits of using `exampleSite`? I'm open to reverting back to using it, but whats the killer reason?

**Comment by JugglerX** [comment]
We have changed back to the exampleSite structure
